### PR TITLE
Fix leak where texel buffer is occasionally accidentally created during image-memory unbinding (#2341)

### LINKED ISSUE #2341: GPU Memory leak on A12Z-based iPad Pro, ATV 4K 1st Gen
Starting with 188a21ad33df4705ea4050f0116939bee097c7fe, on these older devices, I'm seeing a GPU memory leak of about 22MB per second. I don't see it under the same usage scenarios on my M2 Mac or my iPhone 15 Pro.

[ipad.log](https://github.com/user-attachments/files/17038259/ipad.log)

### PR DESCRIPTION
**Pull request by warmenhoven**
Fixes #2341.

### CODE REVIEW

File: MoltenVK/MoltenVK/GPUObjects/MVKImage.mm [hunk 1]
```diff
@@ -2308,7 +2308,10 @@ static void signalAndUntrack(const MVKSwapchainSignaler& signaler) {
 // Memory detached in destructor too, as a fail-safe.
 MVKImageView::~MVKImageView() {
 	detachMemory();
-	_image->release();
+    if (_image) {
+        _image->release();
+        _image = NULL;
```
Comment (cdavis5e) [inline MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:2313]: It shouldn't be necessary to set the `_image` to `nullptr` here, since the object will cease to exist after the destructor is run.

File: MoltenVK/MoltenVK/GPUObjects/MVKImage.mm [hunk 2]
```diff
@@ -2317,6 +2320,10 @@ static void signalAndUntrack(const MVKSwapchainSignaler& signaler) {
 void MVKImageView::destroy() {
 	detachMemory();
 	MVKVulkanAPIDeviceObject::destroy();
+    if (_image) {
+        _image->release();
+        _image = NULL;
+    }
```
Comment (cdavis5e) [inline MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:2326]: So, the reason that `MVKBaseObject::destroy()` exists in the first place is that Metal could still indirectly reference one of these objects even after the Vulkan spec says it's OK to destroy them, through a completion block. These objects are `retain()`ed so that this case doesn't crash. The objects should still be destroyed after the completion blocks have finished running.

Releasing the image here could cause a crash later on. Why is this here? Are you seeing a case where the `MVKImage` and `MVKImageView` objects are getting leaked?

**Review by cdavis5e — CHANGES_REQUESTED** [review]

File: MoltenVK/MoltenVK/GPUObjects/MVKImage.mm (hunk 2 above)
Comment (warmenhoven) [reply MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:2326]: > Are you seeing a case where the MVKImage and MVKImageView objects are getting leaked?

I am, but only on some older hardware, and not in all cases. I only notice the leak after/as a result of 188a21ad33df4705ea4050f0116939bee097c7fe, and if I revert that I no longer see it. It's been sort of hard for me to narrow down the specific case that's causing the leak.

I understand what you're saying though. I'll see if I can go through and figure out which objects are being destroy()'d but not having their destructors called, and where that destroy() is coming from.

Comment (warmenhoven) [reply MoltenVK/MoltenVK/GPUObjects/MVKImage.mm]: I've updated my PR based on my investigation that I've documented in #2341 ; basically `MVKImageMemoryBinding::bindMemoryAddress()` ends up getting called from the `MVKDeviceMemory` destructor with a `nullptr`, but because `_image->_isLinearForAtomics` is true it allocates a buffer that never gets freed.

File: MoltenVK/MoltenVK/GPUObjects/MVKImage.mm [hunk 3]
```diff
@@ -419,7 +419,7 @@
     // macOS before 10.15.5 cannot use shared memory for texel buffers.
     usesTexelBuffer = usesTexelBuffer && (mtlFeats.sharedLinearTextures || !isMemoryHostCoherent());
 
-    if (_image->_isLinearForAtomics || (usesTexelBuffer && mtlFeats.placementHeaps)) {
+    if ((_deviceMemory && _image->_isLinearForAtomics) || (usesTexelBuffer && mtlFeats.placementHeaps)) {
```
Comment (cdavis5e) [inline MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:422]: I apologize for the extra churn, but it occurs to me that the entire `if`-`else` chain ought to be guarded by `if (_deviceMemory)`. Then the null check on line 428 could go away.

**Review by cdavis5e — CHANGES_REQUESTED** [review]
Looks good. Just one small thing.

File: MoltenVK/MoltenVK/GPUObjects/MVKImage.mm (hunk 3 above)
Comment (warmenhoven) [reply MoltenVK/MoltenVK/GPUObjects/MVKImage.mm]: Not a problem at all. I had originally put together a change that bailed out early and decided it would be safer to do something more targeted; but because `_deviceMemory` effectively gets checked in so many places, the entire function ends up being a no-op after the `MVKResource::bindDeviceMemory` call.

**Review by cdavis5e — APPROVED** [review]

File: MoltenVK/MoltenVK/GPUObjects/MVKImage.mm [hunk 4]
```diff
@@ -412,8 +412,12 @@
     if (_deviceMemory) { _deviceMemory->removeImageMemoryBinding(this); }
     MVKResource::bindDeviceMemory(mvkMem, memOffset);
 
+    if (!_deviceMemory) {
+        return VK_SUCCESS;
+    }
```
Comment (billhollings) [inline MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:417]: MoltenVK style typically has this kind of trivial `if` statement on a single line. See for instance line 412 immediately above. Can you compress it please?

File: MoltenVK/MoltenVK/GPUObjects/MVKImage.mm [hunk 5]
```diff
@@ -425,7 +429,7 @@
             _mtlTexelBufferOffset = getDeviceMemoryOffset();
         } else {
             // Create our own buffer for this.
```
Comment (billhollings) [inline MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:431]: Technically, the Vulkan spec mandates a memory-binding activity should only occur once for an image, meaning this function should only ever be called once by the app. But just to make the leak protection a little bit more defensive in case an app makes a mistake, it might be a good to include the following line in between this comment and  the `if()` statement:

```
if (_ownsTexelBuffer) { [_mtlTexelBuffer release]; }
```

**Review by billhollings — CHANGES_REQUESTED** [review]
Thanks for submitting this PR. 

And thanks for all your incredible detective work! I appreciate you digging into this so thoroughly! Great catch!

LGTM. Just a couple of very minor style and robustness requests.

And when amending this, can you modify the commit message to match the updated fix, please? I was able to change the PR description, but I can't change the commit message itself. 

Thanks.

**Comment by warmenhoven** [comment]
I've updated the PR for the wording, the style, and the extra defensive check, and it's all running well for me. Thanks very much!

> Out of curiosity, under what conditions was vkFreeMemory() being called so frequently on every frame?

I wish I could say I understood [Granite](https://github.com/Themaister/Granite) well enough to explain what it's doing [here](https://github.com/Themaister/Granite/blob/533740fe9a443ad48c81df22548736c10faa88b4/vulkan/device.cpp#L2816). My exact test case is just running the [Nintendo 64 RetroArch core](https://github.com/libretro/mupen64plus-libretro-nx/tree/develop) using its [Vulkan renderer](https://github.com/libretro/mupen64plus-libretro-nx/tree/develop/mupen64plus-video-paraLLEl).

**Review by billhollings — APPROVED** [review]
LGTM now. Thanks!
