### PR TITLE
Fix uninitialized MVKImage member.

### LINKED ISSUE #2168: Texture creation crashing in b56c152a1245
This is on an Apple M1 system.

Since yesterday's merge at revision b56c152a1245a95e7d4e8d64baca8ae42e85ae6a (`Merge pull request #2164 from js6i/native-atomics`), texture creation has been crashing in my game. If I build my game with MoltenVK revision 37361ccd5595ff08c050981856903713f96221d2 then the problem goes away.

When running the application directly, I get:
```
_mtlValidateStrideTextureParameters:1864: failed assertion `Texture Descriptor Validation
Linear texture: cannot be mipmapped, mipmapLevelCount (6) disallowed
'
```

When running with Xcode (and Metal API validation enabled), the error message changes a bit:
```
-[MTLDebugBuffer newTextureWithDescriptor:offset:bytesPerRow:]:283: failed assertion `New Texture With Descriptor Validation
linear texture mipmapLevelCount(6) must be 1
```

The callstack of the crash:
```
#0	0x00000001843160dc in __pthread_kill ()
#1	0x0000000100ebac50 in pthread_kill ()
#2	0x0000000184259a40 in abort ()
#3	0x0000000184258d30 in __assert_rtn ()
#4	0x000000018e634694 in MTLReportFailure.cold.1 ()
#5	0x000000018e611508 in MTLReportFailure ()
#6	0x000000018e607468 in _MTLMessageContextEnd ()
#7	0x0000000184b9c64c in -[MTLDebugBuffer newTextureWithDescriptor:offset:bytesPerRow:] ()
#8	0x000000010166c28c in -[CaptureMTLBuffer newTextureWithDescriptor:offset:bytesPerRow:] ()
#9	0x00000001029d0c9c in MVKImagePlane::getMTLTexture() at /Users/steven/Development/darwinia/contrib/angle/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:57
#10	0x00000001029d6c2c in MVKImage::hasPixelFormatView(unsigned int) [inlined] at /Users/steven/Development/darwinia/contrib/angle/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKImage.h:315
#11	0x00000001029d6c20 in MVKImageViewPlane::initSwizzledMTLPixelFormat(VkImageViewCreateInfo const*) at /Users/steven/Development/darwinia/contrib/angle/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:1826
#12	0x00000001029d785c in MVKImageViewPlane::MVKImageViewPlane(MVKImageView*, unsigned char, MTLPixelFormat, VkImageViewCreateInfo const*) [inlined] at /Users/steven/Development/darwinia/contrib/angle/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:1610
#13	0x00000001029d7838 in MVKImageViewPlane::MVKImageViewPlane(MVKImageView*, unsigned char, MTLPixelFormat, VkImageViewCreateInfo const*) [inlined] at /Users/steven/Development/darwinia/contrib/angle/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:1604
#14	0x00000001029d7838 in MVKImageView::MVKImageView(MVKDevice*, VkImageViewCreateInfo const*) at /Users/steven/Development/darwinia/contrib/angle/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:2078
#15	0x0000000102a1757c in MVKDevice::createImageView(VkImageViewCreateInfo const*, VkAllocationCallbacks const*) at /Users/steven/Development/darwinia/contrib/angle/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm:3868
#16	0x00000001029ab518 in vkCreateImageView at /Users/steven/Development/darwinia/contrib/angle/MoltenVK/MoltenVK/MoltenVK/Vulkan/vulkan.mm:964
#17	0x0000000106f77a0c in rx::vk::ImageView::init(VkDevice_T*, VkImageViewCreateInfo const&) [inlined] at /Users/steven/Development/darwinia/contrib/angle/angle/src/libANGLE/renderer/vulkan/vk_wrapper.h:1432
#18	0x0000000106f779f4 in rx::vk::ImageHelper::initLayerImageViewImpl(rx::vk::Context*, gl::TextureType, unsigned int, gl::SwizzleState const&, rx::vk::ImageView*, gl::LevelIndexWrapper<unsigned int>, unsigned int, unsigned int, unsigned int, VkFormat, unsigned int, gl::YuvSamplingMode) const at /Users/steven/Development/darwinia/contrib/angle/angle/src/libANGLE/renderer/vulkan/vk_helpers.cpp:6241
#19	0x0000000106f82a24 in rx::vk::ImageHelper::initLayerImageView(rx::vk::Context*, gl::TextureType, unsigned int, gl::SwizzleState const&, rx::vk::ImageView*, gl::LevelIndexWrapper<unsigned int>, unsigned int, unsigned int, unsigned int, gl::SrgbWriteControlMode, gl::YuvSamplingMode, unsigned int) const [inlined] at /Users/steven/Development/darwinia/contrib/angle/angle/src/libANGLE/renderer/vulkan/vk_helpers.cpp:6165
#20	0x0000000106f829ec in rx::vk::ImageViewHelper::initReadViewsImpl(rx::ContextVk*, gl::TextureType, rx::vk::ImageHelper const&, gl::SwizzleState const&, gl::SwizzleState const&, gl::LevelIndexWrapper<unsigned int>, unsigned int, unsigned int, unsigned int, unsigned int) at /Users/steven/Development/darwinia/contrib/angle/angle/src/libANGLE/renderer/vulkan/vk_helpers.cpp:10849
#21	0x0000000106f82834 in rx::vk::ImageViewHelper::initReadViews(rx::ContextVk*, gl::TextureType, rx::vk::ImageHelper const&, gl::SwizzleState const&, gl::SwizzleState const&, gl::LevelIndexWrapper<unsigned int>, unsigned int, unsigned int, unsigned int, bool, unsigned int) at /Users/steven/Development/darwinia/contrib/angle/angle/src/libANGLE/renderer/vulkan/vk_helpers.cpp:10806
#22	0x0000000106f30d38 in rx::TextureVk::initImageViews(rx::ContextVk*, unsigned int) at /Users/steven/Development/darwinia/contrib/angle/angle/src/libANGLE/renderer/vulkan/TextureVk.cpp:3770
#23	0x0000000106f30898 in rx::TextureVk::initImage(rx::ContextVk*, angle::FormatID, angle::FormatID, rx::ImageMipLevels) at /Users/steven/Development/darwinia/contrib/angle/angle/src/libANGLE/renderer/vulkan/TextureVk.cpp:3740
#24	0x0000000106f301c4 in rx::TextureVk::setStorageMultisample(gl::Context const*, gl::TextureType, int, int, gl::Extents const&, bool) at /Users/steven/Development/darwinia/contrib/angle/angle/src/libANGLE/renderer/vulkan/TextureVk.cpp:1729
#25	0x0000000107068cd8 in gl::Texture::setStorage(gl::Context*, gl::TextureType, int, unsigned int, gl::Extents const&) at /Users/steven/Development/darwinia/contrib/angle/angle/src/libANGLE/Texture.cpp:1761
#26	0x0000000106fef614 in gl::Context::texStorage2D(gl::TextureType, int, unsigned int, int, int) at /Users/steven/Development/darwinia/contrib/angle/angle/src/libANGLE/Context.cpp:6448
#27	0x00000001000f4fd4 in BitmapRGBA::UploadTextureData(Texture::Storage, unsigned int, unsigned int, unsigned int, unsigned char*) [inlined] at /Users/steven/Development/darwinia/code/lib/bitmap.cpp:308
```

The game uses ANGLE's Vulkan backend with MoltenVK for rendering. It's trying to create a swizzled 256x256 GL_RG8 texture with 6 mip levels.

Here's a demo game build with symbols if that helps:
https://www.uplinklabs.net/files/Darwinia-macOS-demo-2.3.2-1108-g98f6e5d4a.zip

### PR DESCRIPTION
**Pull request by js6i**
Fix up for #2164, fixes #2168.

### CODE REVIEW

File: MoltenVK/MoltenVK/GPUObjects/MVKImage.mm [hunk 1]
```diff
@@ -939,6 +939,7 @@
 				((_vkFormat == VK_FORMAT_R32_UINT || _vkFormat == VK_FORMAT_R32_SINT) ||
 					(_hasMutableFormat && pixFmts->getViewClass(_vkFormat) == MVKMTLViewClass::Color32 && (getIsValidViewFormat(VK_FORMAT_R32_UINT) || getIsValidViewFormat(VK_FORMAT_R32_SINT))));
 
+	_isLinearForAtomics = false;
 	if (_shouldSupportAtomics && !getPhysicalDevice()->useNativeTextureAtomics())
 		_isLinearForAtomics = _arrayLayers == 1 && getImageType() == VK_IMAGE_TYPE_2D;
```
Comment (billhollings) [inline MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:944]: Probably better to combine these into one operation to improve stability and readability.

```suggestion
	_isLinearForAtomics = _shouldSupportAtomics && !getPhysicalDevice()->useNativeTextureAtomics() && _arrayLayers == 1 && getImageType() == VK_IMAGE_TYPE_2D;
```

**Review by billhollings — CHANGES_REQUESTED** [review]
Thanks for catching this, and providing a fix!

Looks good. I've just requested a syntax consolidation to improve readability and stability.

**Review by billhollings — APPROVED** [review]
Thanks.
