### PR TITLE
Fix rare deadlock during launch via dlopen().

### LINKED ISSUE #2050: Deadlock when loading MVK dynamically
When using MVK with wine and ffxiv there is a rare deadlock (about 1 in 50 game starts):

```
  Thread 0x202702    DispatchQueue "com.Metal.DeviceDispatch"(258)    44 samples (1-44)    priority 47 (base 47)
  <thread QoS user interactive (requested user initiated, promote user interactive, workloop servicer override user initiated), process unclamped, process received importance donation from WindowServer [364], process received importance donation from CursorUIViewService [834], IO tier 0>
  44  start_wqthread + 15 (libsystem_pthread.dylib + 7063) [0x7ff8064c0b97] 1-44
    44  _pthread_wqthread + 327 (libsystem_pthread.dylib + 11335) [0x7ff8064c1c47] 1-44
      44  _dispatch_workloop_worker_thread + 451 (libdispatch.dylib + 78845) [0x7ff80632d3fd] 1-44
        44  _dispatch_root_queue_drain_deferred_wlh + 271 (libdispatch.dylib + 80622) [0x7ff80632daee] 1-44
          44  _dispatch_lane_invoke + 377 (libdispatch.dylib + 41216) [0x7ff806324100] 1-44
            44  _dispatch_lane_serial_drain + 1076 (libdispatch.dylib + 38764) [0x7ff80632376c] 1-44
              44  _dispatch_client_callout + 8 (libdispatch.dylib + 13722) [0x7ff80631d59a] 1-44
                44  CA::CG::Queue::render_callback(void*) + 54 (QuartzCore + 335590) [0x7ff80ef31ee6] 1-44
                  44  CA::CG::AccelRenderer::acquire(CA::CG::AccelDrawable&, CA::CG::AccelRenderer**, unsigned long long, unsigned int, bool, __CFString const*) + 638 (QuartzCore + 2994954) [0x7ff80f1bb30a] 1-44
                    44  CAMetalContextCreateWithGPURegistryID + 58 (QuartzCore + 337975) [0x7ff80ef32837] 1-44
                      44  MTLCopyAllDevices + 189 (Metal + 5229) [0x7ff810dc946d] 1-44
                        44  _dispatch_once_callout + 20 (libdispatch.dylib + 18379) [0x7ff80631e7cb] 1-44
                          44  _dispatch_client_callout + 8 (libdispatch.dylib + 13722) [0x7ff80631d59a] 1-44
                            44  invocation function for block in MTLDeviceArrayInitialize() + 1457 (Metal + 192782) [0x7ff810df710e] 1-44
                              44  MTLRegisterDevices + 198 (Metal + 1447242) [0x7ff810f2954a] 1-44
                                44  _dispatch_lane_barrier_sync_invoke_and_complete + 60 (libdispatch.dylib + 66631) [0x7ff80632a447] 1-44
                                  44  _dispatch_client_callout + 8 (libdispatch.dylib + 13722) [0x7ff80631d59a] 1-44
                                    44  +[MTLIOAccelService registerService:] + 142 (Metal + 5765) [0x7ff810dc9685] 1-44
                                      44  -[MTLIOAccelService initWithAcceleratorPort:] + 340 (Metal + 6143) [0x7ff810dc97ff] 1-44
                                        44  getMetalPluginClassForService + 327 (Metal + 1446351) [0x7ff810f291cf] 1-44
                                          44  -[NSBundle classNamed:] + 33 (Foundation + 499354) [0x7ff8074b5e9a] 1-44
                                            44  -[NSBundle loadAndReturnError:] + 391 (Foundation + 400431) [0x7ff80749dc2f] 1-44
                                              44  _CFBundleLoadExecutableAndReturnError + 243 (CoreFoundation + 1109010) [0x7ff806632c12] 1-44
                                                44  _CFBundleDlfcnLoadBundle + 223 (CoreFoundation + 670032) [0x7ff8065c7950] 1-44
                                                  44  dyld4::APIs::dlopen_from(char const*, int, void*) + 479 (dyld + 232221) [0x214038b1d] 1-44
                                                    44  __ulock_wait + 10 (libsystem_kernel.dylib + 12770) [0x7ff8064871e2] 1-44
                                                     *44  ??? (kernel.release.t6020 + 5755004) [0xfffffe0008ac107c] (blocked by turnstile waiting for ffxiv_dx11.exe [63906] [unique pid 163100] thread 0x2026c5) 1-44

  Thread 0x2026c4    Thread name "com.apple.rosetta.exceptionserver"    44 samples (1-44)    priority 31 (base 31)
  <process unclamped, process received importance donation from WindowServer [364], process received importance donation from CursorUIViewService [834], IO tier 0>
  44  ??? (runtime + 73264) [0x7ff7fffc9e30] 1-44
    44  <patched truncated backtrace> 1-44
      44  ??? (runtime + 17076) [0x7ff7fffbc2b4] 1-44
       *44  ??? (kernel.release.t6020 + 227704) [0xfffffe000857b978] 1-44

  Thread 0x2026c5    44 samples (1-44)    priority 47 (base 47)
  <thread QoS user interactive (requested user interactive, promote user interactive), process unclamped, process received importance donation from WindowServer [364], process received importance donation from CursorUIViewService [834], IO tier 0>
  44  ??? [0x17005a580] 1-44
    44  ??? (winemac.drv.so + 250827) [0x6aee23cb] 1-44
      44  dyld4::APIs::dlopen_from(char const*, int, void*) + 935 (dyld + 232677) [0x214038ce5] 1-44
        44  dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const + 93 (dyld + 114387) [0x21401bed3] 1-44
          44  dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const + 98 (dyld + 126860) [0x21401ef8c] 1-44
            44  dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 181 (dyld + 114237) [0x21401be3d] 1-44
              44  dyld4::JustInTimeLoader::runInitializers(dyld4::RuntimeState&) const + 21 (dyld + 136875) [0x2140216ab] 1-44
                44  dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const + 222 (dyld + 113736) [0x21401bc48] 1-44
                  44  dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 390 (dyld + 393914) [0x2140602ba] 1-44
                    44  dyld3::MachOFile::forEachInitializerPointerSection(Diagnostics&, void (unsigned int, unsigned int, bool&) block_pointer) const + 116 (dyld + 352516) [0x214056104] 1-44
                      44  dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 176 (dyld + 342748) [0x214053adc] 1-44
                        44  dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 249 (dyld + 8319) [0x21400207f] 1-44
                          44  invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 543 (dyld + 346387) [0x214054913] 1-44
                            44  invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 133 (dyld + 394628) [0x214060584] 1-44
                              44  invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const + 182 (dyld + 126742) [0x21401ef16] 1-44
                                44  _GLOBAL__sub_I_mvk_datatypes.mm + 23 (libMoltenVK.stable.dylib + 4556695) [0x76e9c797] 1-44
                                  44  MVKPixelFormats::MVKPixelFormats(MVKPhysicalDevice*) + 350 (libMoltenVK.stable.dylib + 412014) [0x76aa896e] 1-44
                                    44  MVKPixelFormats::modifyMTLFormatCapabilities() + 48 (libMoltenVK.stable.dylib + 423648) [0x76aab6e0] 1-44
                                      44  MTLCopyAllDevices + 189 (Metal + 5229) [0x7ff810dc946d] 1-44
                                        44  _dispatch_once_wait + 79 (libdispatch.dylib + 15680) [0x7ff80631dd40] 1-44
                                          44  __ulock_wait + 10 (libsystem_kernel.dylib + 12770) [0x7ff8064871e2] 1-44
                                           *44  ??? (kernel.release.t6020 + 5755004) [0xfffffe0008ac107c] (blocked by turnstile waiting for ffxiv_dx11.exe [63906] [unique pid 163100] thread 0x202702) 1-44
```

The problem here is that `dlopen_from` has a global lock, as does `_dispatch_once_wait` for `MTLCopyAllDevices`, or in other words MVK cannot call `MTLCopyAllDevices` when being loaded dynamically in its initialization (inside `dlopen_from`), since another thread calling `MTLCopyAllDevices` in parallel will acquire the `_dispatch_once_wait` lock for `MTLCopyAllDevices` and then deadlocks on the `dlopen_from` global lock, which is being held by MVK waiting for the `MTLCopyAllDevices` libdispatch lock.

### PR DESCRIPTION
**Pull request by billhollings**
- Don't create global `MVKPixelFormats` instance during launch, as this triggers a call to `MTLCopyAllDevices()`, which can deadlock if app is also launching other services that use Metal.

Fixes #2050.

### CODE REVIEW

File: MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm [hunk 1]
```diff
@@ -32,111 +32,116 @@
 
 #pragma mark Pixel formats
 
-static MVKPixelFormats _platformPixelFormats;
+static MVKPixelFormats* _platformPixelFormats = nullptr;
+
+static MVKPixelFormats* getPlatformPixelFormats() {
+	if ( !_platformPixelFormats ) { _platformPixelFormats = new MVKPixelFormats(); }
+	return _platformPixelFormats;
+}
```
Comment (juan-lunarg) [inline MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:40]: What about using a `std::unique_ptr`? Avoids minor issue when running MoltenVK via address sanitizer since I don't see the memory being freed.

Comment (cdavis5e) [reply MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:40]: I was going to say, "there needs to be a dylib termination function to free this object," but yeah, a `std::unique_ptr` would fit the bill.

File: MoltenVK/MoltenVK/API/mvk_datatypes.h [hunk 2]
```diff
@@ -34,6 +34,8 @@ extern "C" {
  *
  * The functions here are used internally by MoltenVK, and are exposed here
  * as a convenience for use elsewhere within applications using MoltenVK.
+ * These functions can only be used if the application is linked directly 
+ * to MoltenVK, and not dynamically through the Vulkan Loader.
```
Comment (cdavis5e) [inline MoltenVK/MoltenVK/API/mvk_datatypes.h:38]: Is this true anymore? Calling any of these functions should result in a call to `getPlatformPixelFormats()`, which should initialize the `_platformPixelFormats` object.

**Review by cdavis5e — CHANGES_REQUESTED** [review]

File: MoltenVK/MoltenVK/API/mvk_datatypes.h (hunk 2 above)
Comment (billhollings) [reply MoltenVK/MoltenVK/API/mvk_datatypes.h:38]: It wasn't that. It's that the MoltenVK SDK build hides many of the linkable functions within MoltenVK. That's the purpose of `MVK_PUBLIC_VULKAN_SYMBOL` and `MVK_HIDE_VULKAN_SYMBOLS`. 

Also, there is a strong push towards SDK MoltenVK not being accessed except through supported Vulkan API functions. This is why MoltenVK will be supporting `VK_EXT_layout_settings`. The idea for this is to avoid user confusion and complaints when they can't access MoltenVK functions through the Vulkan layers.

However, the `mvk_datatypes.mm` functions are marked with `MVK_PUBLIC_SYMBOL`, so they will always be exposed, and they don't interact with Vulkan API calls at all, or involve passing layer objects. So in a technical sense, you are accurate, and I've removed the comment.

**Comment by richard-lunarg** [comment]
I was hopeful when I saw this PR that it would fix a problem I've encountered with Qt frameworks that just started two releases ago. There's a deadlock somewhere (and Qt is using Metal for it's own GUI) as the GUI never shows up, although    the render loop runs, and there are no validation errors. The error I'm encountering happens if I link statically, or use the Loader. This is a good fix, I'm just putting out there that there may be more deadlocks like this floating around.

File: MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm (hunk 1 above)
Comment (billhollings) [reply MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:40]: Thanks both for the catch.

I got cheeky knowing that it will only be deleted while the library is being shut down. Although I suppose with `dylibs` that might not mean the end of proc memory. And, anyway, it's best to play nice with RAII. 

I've added the `unique_ptr`

**Comment by billhollings** [comment]
> I was hopeful when I saw this PR that it would fix a problem I've encountered with Qt frameworks that just started two releases ago.

Thanks for reporting it. 

Uggh. If you have more info about the Qt deadlock, can you open another issue focused on it, please?

File: MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm [hunk 3]
```diff
@@ -32,111 +32,116 @@
 
 #pragma mark Pixel formats
 
-static MVKPixelFormats _platformPixelFormats;
+static std::unique_ptr<MVKPixelFormats> _platformPixelFormats;
+
+static MVKPixelFormats* getPlatformPixelFormats() {
+	if ( !_platformPixelFormats ) { _platformPixelFormats.reset(new MVKPixelFormats()); }
```
Comment (juan-lunarg) [inline MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:38]: Use std::make_unique C++14

https://github.com/AnthonyCalandra/modern-cpp-features#stdmake_unique

```suggestion
	if ( !_platformPixelFormats ) { _platformPixelFormats = std::make_unique<MVKPixelFormats>(); }
```

Comment (cdavis5e) [reply MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:38]: I actually don't mind either way. Of the three justifications listed, two don't apply here. The type of the pointer is already specified, because it is a global object. And there aren't multiple calls that could throw an exception in that expression. As for the first, avoiding using `new` directly, this project uses `new` extensively.

**Review by cdavis5e — APPROVED** [review]

File: MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm (hunk 3 above)
Comment (juan-lunarg) [reply MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:38]: Agreed doesn't really matter. Just thought I would throw it out there.

**Review by juan-lunarg — APPROVED** [review]

File: MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm (hunk 3 above)
Comment (billhollings) [reply MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm:38]: > Agreed doesn't really matter. Just thought I would throw it out there.

Excellent observation! I didn't consider C++14 options. 

But, I do prefer the existing form, as it explicitly matches the `new MVKObj()` form found elsewhere, and feels more like the activity telling the existing empty `unique_ptr` to "manage this now". 

Now, if only the function was called `set()`, instead of `reset()`, to match the corresponding `get()`. 😉
