### PR TITLE
Fixes #1390 - when MVKRenderSubpass::populateClearAttachments determi…

### LINKED ISSUE #1390: MoltenVK incorrectly clearing stencil when only depth is set to clear [Dota]
I ran into a bug in Dota which is causing the water to render black when setting "Game Screen Render Quality" to less than 100%.  I noticed this when testing the new AMD FidelityFX Super Resolution feature that we added.

The problem is that there is a renderpass that has a renderArea smaller than the attachments and it has Color and Depth clear set to loadOp CLEAR and stencilLoadOp to LOAD.  I've found the bug where MoltenVK is incorrectly clearing stencil in this case, I'll file a PR shortly, but wanted to open a tracking issue.

### PR DESCRIPTION
**Pull request by danginsburg**
…nes whether to clear stencil, it was using the loadOp for the depth.  It needs to look at the loadOp for the stencil which is set independently.

### CODE REVIEW

**Review by billhollings — APPROVED** [review]
Thanks, Dan!

File: MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h [hunk 1]
```diff
@@ -201,6 +201,9 @@ class MVKRenderPassAttachment : public MVKBaseObject {
     /** Returns whether this attachment should be cleared in the subpass. */
     bool shouldUseClearAttachment(MVKRenderSubpass* subpass);
 
+    /** Returns stencil attachment load op */
```
Comment (cdavis5e) [inline MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h:204]: Doc comments should be complete sentences. Also, this one doesn't have any information that couldn't be inferred from the method name.

**Review by cdavis5e — APPROVED** [review]
Looks good. Just one really minor nit.

File: MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h (hunk 1 above)
Comment (danginsburg) [reply MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h]: Added clarifying comment that is a complete sentence :)
