### PR TITLE
Occlusion query fixes for M1

### LINKED ISSUE #1385: Query pool CTS tests failing on M1
Strangely, for the CTS tests in `vk-default/query-pool.txt`:

- AMD & Intel: Pass: 188 / Fail:  0.
- M1: Pass: 48 / Fail: 140.

The M1 numbers can sometimes change, indicating some form of race condition. Some failing tests can pass occasionally when running in batch, but always fail when run alone.

It seems to be connected to those tests that have multiple render passes with occlusion queries in them. Subsequent renderpass queries seem to be overwriting, or corrupting previous ones, but in ways that have no obvious cause as yet. The writes seem to be occurring to the correct buffer offsets, and appear so in GPU capture, but then the buffer offsets seem to be shifted when reading the contents back to the CPU for test verification.

I'm currently looking into this.

@cdavis5e I'm continuing with this...but if any possible causes pop into your head, feel free to suggest paths for me to research. So far I have eliminated the type of Vulkan wait used before the CPU read, and buffer alignment corruption on the copy from temporary buffer to visibility buffer. Next attempt will be to see if M1 somehow requires `MTLFences` or `MTLEvents` on the `MTLBuffers` between visibility compute encoders (which it shouldn't per docs).

### PR DESCRIPTION
**Pull request by billhollings**
Fixes #1385.

Per discussion in issue, this PR allows a single Metal visibility buffer to be used for all render encoders in a single `MTLCommandBuffer`.

- The first commit in this PR fixes the issue across multiple Metal render encoders in a single Vulkan command buffer.
- The second commit here extends this to an entire Vulkan submit (multiple Vulkan command buffers, one Metal command buffer).
- Third commit cleans up some syntax around tracking query locations in the visibility buffer to make it clearer how the mapping works.

### CODE REVIEW

File: MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm [hunk 1]
```diff
@@ -799,6 +799,33 @@
...
+}
+
+
+#pragma mark -
+#pragma mark MVKCommandEncodingContext
+
+// Increment to the next query slot offset. If we reach the size of the visibility buffer,
+// reset to retrieve and start filling another visibility buffer. This approach may still
+// cause Metal validation errors if the platform does not permit offsets to be reused
+// witin a MTLCommandBuffer, even when a different visibility buffer is used.
```
Comment (cdavis5e) [inline MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm:812]:
```suggestion
// within a MTLCommandBuffer, even when a different visibility buffer is used.
```

File: MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm [hunk 2]
```diff
@@ -799,6 +799,33 @@
...
+// We don't test against the size of the visibility buffer itself, because this call may
+// arrive before the visibiltiy buffer in the case of a query that ends before the renderpass.
```
Comment (cdavis5e) [inline MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm:814]:
```suggestion
// arrive before the visibility buffer in the case of a query that ends before the renderpass.
```

**Review by cdavis5e — APPROVED** [review]
Just a couple of minor typos.

**Comment by js6i** [comment]
I'm trying to understand what happens when we overflow the buffer. Suppose we only have one slot left in the visibility buffer and we begin a render pass, start a query, draw, end query and start another one, draw again, end, get the results. I'm likely missing something, but:
1) Shouldn't we use a new `MTLRenderPipelineState` after we've ran out of space and made a new buffer? The buffer is baked into it.
2) We only get the newest buffer in `MVKOcclusionQueryCommandEncoderState::endMetalRenderPass`, so shouldn't we also force an accumulation step when we change buffers? Or, better, remember which one was used for each query?
3) If the answer to above is that in the end we only use the new buffer for the whole Metal render pass during which the old buffer overflowed, we still seem to have old (high) offsets in the query array, which might get accidentally reused later?

I'm guessing that the Metal render pass *is* ended somehow in this scenario, or things happen in some different order than I think they do.

**Comment by billhollings** [comment]
>1. Shouldn't we use a new MTLRenderPipelineState after we've ran out of space and made a new buffer? The buffer is baked into it.

Not `MTLRenderPipelineState`. The visibility buffer is baked into `MTLRenderCommandEncoder`, which is created on boundaries of Vulkan subpasses (BeginRenderpass or NewSubpass).

The `incrementMTLVisibilityResultOffset` that triggers the need for a new buffer occurs at the end of an occlusion query. The creation of that new buffer occurs at the beginning of a render pass.

So the situation you describe would be the end of an occlusion query but before the next renderpass. Subsequent queries in that renderpass would overwrite the beginning of the visibility buffer (which may or may not cause a validation error depending on the platform). Subsequent render passes would use the new visibility buffer.

> 2. We only get the newest buffer in MVKOcclusionQueryCommandEncoderState::endMetalRenderPass, so shouldn't we also force an accumulation step when we change buffers? Or, better, remember which one was used for each query?

Yes. Perhaps we should track the visibility buffer in the `OcclusionQueryLocation`. But I think the same situation I described above would occur. The new visibility buffer would not make it into the current renderpass encoder, and queries used in that renderpass would overwrite the beginning of the visibility buffer. 

Or...in both cases, maybe we could detect that the buffer has changed and avoid those overwrites in the current renderpass.

Another simpler and predictable option could be to just use one visibility buffer and permit only up to the maximun numbers of queries per `MTLCommandBuffer`, and just trigger a Vulkan error when it is exceeded.

**Comment by js6i** [comment]
Maybe we could simply restart the encoder (`MVKCommandEncoder::beginMetalRenderPass`?) when we overflow the buffer? We'd accumulate all queries, resume any active ones with the offsets they had assigned and move on - we shouldn't ever reach these old offsets and still need them, as that would mean the render pass limit of queries was exceeded.

**Comment by billhollings** [comment]
In the end I decided to keep this simple until we have a definite need to do further gymnastic workarounds.

I have reverted to just supporting one Metal visibility buffer per `MTLCommandBuffer`, outputting an error log and safely halting visibility tracking within the `MTLCommandBuffer` if the visibility buffer becomes exhausted.

> Maybe we could simply restart the encoder

Hmmm...this sounded fraught with side effects, so I didn't dig into it. It remains a possibility if we identify that we need more flexibility with tracking larger numbers of occlusion queries in a single Vulkan submit.

> we could track the need to allocate a new visibility buffer for a render pass before we start encoding it

So we have #1256 proposing a finer level of tracking the need for a visibility buffer. But again, it appears to be a fairly complex solution to an ill-defined need. Something for the future if needed.

**Review by cdavis5e — APPROVED** [review]

**Review by js6i — APPROVED** [review]
